# frozen_string_literal: true

# Homebrew cask for Visual Beads.
#
# Generated by scripts/release.sh — do not edit the rendered copy. The version
# and checksum have to match the artefact exactly, and a cask edited by hand is
# how they come to disagree with what the app reports.
#
# It lives in a personal tap rather than homebrew/homebrew-cask: that repository
# requires software with a track record, and submitting a newly published app
# costs a review cycle for a predictable no. See docs/project_notes/DECISIONS.md.
#
# The layout below is not free-form — `brew style` enforces it, and
# `./scripts/release.sh --lint-cask` runs that check without needing a build.
# Stanza grouping, the alphabetised `zap` array and the frozen-string comment
# are all its doing, so keep them when editing.
cask "vbx" do
  version "0.1.0"
  sha256 "daef05239735c78e2d41af932d37be1b224b1792d311a9fd445de635efccb6fa"

  url "https://github.com/michel-onstein/vbx/releases/download/0.1.0/vbx-0.1.0.dmg",
      verified: "github.com/michel-onstein/vbx/"
  name "Visual Beads"
  # No platform in a cask description — `Cask/Desc` rejects "macOS" here, since
  # every cask is macOS.
  desc "Visual front end for beads issue graphs"
  homepage "https://github.com/michel-onstein/vbx"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :sonoma"

  # The bundle on disk is vbx.app — `vbx` is the short form that names the
  # executable, the bundle identifier and the URL scheme. Finder shows it as
  # "Visual Beads" from CFBundleDisplayName.
  app "vbx.app"
  # `brew install --cask vbx` does not put the CLI on the PATH by itself: it is
  # bundled inside the app, mirroring how Xcode ships xcodebuild.
  binary "#{appdir}/vbx.app/Contents/MacOS/vbx-cli", target: "vbx-cli"

  # Alphabetical because `Cask/ArrayAlphabetization` requires it, which is why
  # the preferences file is not first despite being the one that matters most.
  zap trash: [
    "~/Library/Caches/com.qjam.vbx",
    "~/Library/HTTPStorages/com.qjam.vbx",
    # The column layout (`issueListColumnCustomization`) and the recents list.
    "~/Library/Preferences/com.qjam.vbx.plist",
    "~/Library/Saved Application State/com.qjam.vbx.savedState",
  ]

  caveats <<~EOS
    Deploy credentials are kept in the Keychain, which `--zap` cannot reach.
    To remove them:

      security delete-generic-password -s com.qjam.vbx -a github-token
      security delete-generic-password -s com.qjam.vbx -a cloudflare-token
  EOS
end
